# enju
version: '2'
services:
  enju:
    build: ./enju/
  lb:
    image: dockercloud/haproxy
    links:
      - enju
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# postgresql
# postgresql:
#   image: postgres
#   ports:
#     - "5432:5432"
#   volumes:
#     - /home/ec2-user/docker/postgres:/var/lib/postgresql/data
#   environment:
#     - POSTGRES_PASSWORD=postgres
#     - POSTGRES_USER=postgres
# redis
# redis:
#   image: redis
#   ports:
#     - "6379:6379"
# nginx
# nginx:
#   image: nginx
#   ports:
#     - "80:80"
#     - "443:443"
#   volumes:
#     - /var/www/AI-talk-engine/preprocessor/docker/nginx/default.template:/etc/nginx/conf.d/default.template
#     - /etc/letsencrypt:/etc/letsencrypt:ro
#   environment:
#    - NGINX_SERVER_NAME=preprocessor.monogocoro.ai
#    - NGINX_HOST=${HOST_IP}
#    - NGINX_PORT=3000
#   command: /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT$$NGINX_SERVER_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
